String tasks = 'Tasks';
String alltasks = 'AllTasks';
String donetasks = 'Done';
String archivedtasks = 'Archived';
String tasksdb = 'tasks.db';
String tasktitle = 'Task Title';
String date = 'Task Time';
String status = 'status';
String day = 'Task Day';
